services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "${VPN_PORT:-1194}:1194/udp"
    volumes:
      - ./data:/etc/openvpn
    restart: unless-stopped
